version: "3.4"

services:
  proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - ./certs:/etc/nginx/certs:ro

  ssl-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: ssl-companion
    volumes:
      - ./certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - proxy
    environment:
      ACME_CA_URI: https://acme-staging.api.letsencrypt.org/directory

  adminPanel:
    image: nginx
    container_name: adminPanel
    volumes:
      - /docker/adminPanel/html:/usr/share/nginx/html
    environment:
      VIRTUAL_HOST: admin.chaarmiz.com
      LETSENCRYPT_HOST: admin.chaarmiz.com
      LETSENCRYPT_EMAIL: ala@chaarmiz.com

  website:
    image: nginx
    container_name: website
    volumes:
      - /docker/website/html:/usr/share/nginx/html
    environment:
      VIRTUAL_HOST: chaarmiz.com,www.chaarmiz.com
      LETSENCRYPT_HOST: chaarmiz.com
      LETSENCRYPT_EMAIL: ala@chaarmiz.com

  gitlab:
     image: 'gitlab/gitlab-ce:latest'
     ports:
       - '22'
       - '80'
     environment:
       GITLAB_OMNIBUS_CONFIG: |
          external_url 'https://git.chaarmiz.com'
          registry_external_url 'http://registry.chaarmiz.com'
          nginx['listen_port'] = 80
          nginx['listen_https'] = false
          nginx['proxy_set_headers'] = { 'X-Forwarded-Proto' => 'https', 'X-Forwarded-Ssl' => 'on' }
       VIRTUAL_HOST: git.chaarmiz.com,registry.chaarmiz.com
       VIRTUAL_PORT: 80
       LETSENCRYPT_EMAIL: info@example.com
       LETSENCRYPT_HOST: git.chaarmiz.com,registry.chaarmiz.com
       CERT_NAME: git.chaarmiz.com